// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CestaCompra.Aplicacao.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RealizarCompra")]
    public partial class RealizarCompraFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RealizarCompra.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "RealizarCompra", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Sucesso em Realizar Compra")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void SucessoEmRealizarCompra()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sucesso em Realizar Compra", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("Eu acesso <minhas listas de compras>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 9
testRunner.And("Eu seleciono a lista desejada <listaC>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 10
testRunner.And("O sistema sugere a cidade de residência e/ou eu posso selecionar outra cidade <ci" +
                    "dade>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 11
testRunner.And("O sistema retorna <listaS> com os supermercados com o menor preço total em ordem " +
                    "crescente.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 12
testRunner.And("Eu seleciono o <supermercado>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 13
testRunner.And("Eu  pressiono <Realizar Compra>", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 14
testRunner.And("O sistema permite que eu inclua, altere quantidade e preço ou remova itens da lis" +
                    "ta para realizar a compra.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 15
testRunner.When("Eu <confirmo> a compra", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 16
testRunner.Then("O sistema gera uma <novaCompra> e registra no banco de dados .", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Insucesso em Realizar Compra")]
        public virtual void InsucessoEmRealizarCompra()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Insucesso em Realizar Compra", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
testRunner.When("que eu eu não <confirmo> a compra", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 20
testRunner.Then("O sistema não gera uma <novaCompra> e não registra no banco de dados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
