version: 1.0.{build}

environment:
  # postgres
  POSTGRES_PORT: tcp://localhost:5432
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: BancoCestaCompra
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
  PGUSER: postgres
  PGPASSWORD: Password12!
  
init:
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%

services:
  - postgresql96

before_build:
- ps: >-
    cd CestaDeCompras

    nuget restore -verbosity quiet
    
build:
  publish_wap: true
  verbosity: quiet
before_package:
- cmd: >-

before_test:
- cmd: MsBuild.exe /t:Rebuild
- cmd: psql -a -f "C:/projects/cesta-de-compras/ModelagemBanco/ScriptsEntityFramework/CriarBancoDeDados.sql"
- cmd: psql -d BancoCestaCompra -a -f "C:/projects/cesta-de-compras/ModelagemBanco/ScriptsEntityFramework/CriarTabelas.sql" 
- cmd: psql -d BancoCestaCompra -a -f "C:/projects/cesta-de-compras/ModelagemBanco/ScriptsEntityFramework/insertDados.sql" 

after_test:
- cmd: ipconfig

    
    
deploy:
- provider: WebDeploy
  server: https://eduardocoutto-001-site1.htempurl.com:8172/msdeploy.axd?site=eduardocoutto-001-site1
  website: eduardocoutto-001-site1
  username: ifc\eduardocoutto-001
  password:
    secure: Orw8GZWzSrtxBpvT3LK37A==
  on:
    branch: master
    
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#grupo_cesta_basica'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
