version: 1.0.{build}
before_build:
  - cd CestaDeCompras
  - nuget restore
nuget:
  account_feed: true
  project_feed: true
build:
  verbosity: minimal
  publish_wap: true
  
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#grupo_cesta_basica'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
